document.write('<div class="w3-top">');
document.write('<div class="w3-bar w3-black w3-card">');
document.write('<a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="功能表">選單 <i class="fa fa-bars"></i></a>');
document.write('<a href="index.html" class="w3-bar-item w3-button"><img src="images/logo3.png" title="風向基" style="width: 1.8em;"></a>');
document.write('<a href="strategy.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">策略(演算法)市集</a>');
document.write('<a href="tools.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">計算機工具</a>');
document.write('<a href="school.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">投資小學堂</a>');
document.write('<a href="case.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">重大事件</a>');
document.write('<a href="qa.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Q&A</a>');
document.write('<a href="contact.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">聯絡我們</a>');
document.write('<a href="about.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">關於我們</a>');
document.write('<a href="cust_login.html" class="w3-bar-item w3-button w3-padding-large w3-right w3-hover-red">會員登入</a>');
document.write('</div>');
document.write('</div>');